#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)"
MARKER_DIR="$ROOT_DIR/.bootstrap"
MARKER_FILE="$MARKER_DIR/local-venv.done"
PYPROJECT_FILE="$ROOT_DIR/pyproject.toml"

FORCE=0

usage() {
  echo "Usage: $0 [--force]"
  echo
  echo "Bootstraps the local Python 3.12 uv environment once."
  echo "Use --force to run uv sync again after bootstrap has completed."
}

case "${1:-}" in
  "")
    ;;
  "--force")
    FORCE=1
    ;;
  "-h"|"--help")
    usage
    exit 0
    ;;
  *)
    usage
    exit 2
    ;;
esac

if [ -f "$MARKER_FILE" ] && [ "$FORCE" -ne 1 ]; then
  echo "Local venv bootstrap already completed."
  echo "Marker: $MARKER_FILE"
  echo "Use --force to run uv sync again."
  exit 0
fi

cd "$ROOT_DIR"

if ! command -v uv >/dev/null 2>&1; then
  echo "Error: uv is required but was not found on PATH."
  echo "Install uv first, then rerun this script."
  exit 1
fi

if [ ! -f "$PYPROJECT_FILE" ]; then
  cat > "$PYPROJECT_FILE" <<'EOF'
# Generated by scripts/bootstrap/setup-local-venv.sh.
# This file encodes the default Python backend stack for this workspace.
# Existing pyproject.toml files are never overwritten by the bootstrap script.

[project]
name = "fastapi-is-cool"
version = "0.1.0"
description = "Shared FastAPI backend for sibling apps."
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic-settings",
    "sqlalchemy[asyncio]",
    "asyncpg",
    "alembic",
    "python-multipart",
    "orjson",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "httpx",
    "ruff",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
EOF
  echo "Created pyproject.toml with the default FastAPI backend stack."
else
  echo "Found existing pyproject.toml; leaving it unchanged."
fi

if [ ! -d "$ROOT_DIR/.venv" ]; then
  uv venv --python 3.12
else
  echo "Found existing .venv; leaving it in place."
fi

uv sync

mkdir -p "$MARKER_DIR"
{
  echo "completed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "python=3.12"
  echo "tool=uv"
  echo "script=scripts/bootstrap/setup-local-venv.sh"
} > "$MARKER_FILE"

echo "Local venv bootstrap completed."
echo
echo "Next step:"
echo "  scripts/bootstrap/create-app-skeleton.sh"
echo
echo "Before building a Docker image from the clean clone, commit and push generated files such as pyproject.toml and uv.lock."
